services:
  - type: web
    name: erp-nsa
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: NSA_SECRET
        value: MotDePasseNSA2026!
      - key: DATA_DIR
        value: /opt/render/project/data
